title: inkytonik
description: >
  Blog, projects, publications and talks from Anthony Sloane (inkytonik).
permalink: ":title/"
baseurl: ""
url: ""
site-twitter: inkytonik

# Author Settings
author: Anthony Sloane
author-img: Tony66.jpg
about-author:
social-twitter: inkytonik
social-github: inkytonik
social-linkedin: anthonysloane
social-email: inkytonik@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics:

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
